### ISSUE TITLE
Thread safety of agentMemory between gateway and heartbeat

### ISSUE THREAD

**Issue by YangZhou1997** [uwaterloo-mast/malcolm#1]
Dear authors, 

Thanks for open-sourcing the Malcolm code! 

I went through the code, and found there might be some thread safety issues of agentMemory between gateway threads and heartbeat threads. For example, gateway threads would call `agentMemory->incrementServerMigratedTasks` to increase the `serverNumOfMigratedTasks` counter, while heartbeat threads would call `agentMemory->getServerMigratedTasks` to retrieve the `serverNumOfMigratedTasks` counter. However, there seems no thread synchronization between these two. 

I wonder if this would create some issues with load-balancing performance, or if such memory out-of-sync nearly does not nearly impact? 

Best,
Yang

**Comment by smajidzahedi** [comment]
Hi Yang,

`incrementServerMigratedTasks` takes as input an index. This index is incremented in a thread-safe manner by the heartbeat-manager thread (search for `policyAccessGuard.store` in `server.cpp`). This way, we avoid data race by making sure that the gateway thread and the heartbeat-manger thread do not access the same memory location.

**Comment by YangZhou1997** [comment]
Thank you for the explanation!
